[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["Fernthedev"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.57"
# include = ["../protos"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.0.0", features = [] }
protoc-rust = "2"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["full"] }
bytes = "*"
futures = "*"
anyhow = "1.0"
protobuf = { version = "2", features = ["with-bytes"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0", features = ["api-all"] }
log = "0.4"
env_logger = "0.9"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
lto = true
opt-level = 3
