name: Build Qmod

env:
  module_id: questeditor
  qmodName: Quest Editor

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./qmod

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          submodules: true
          lfs: true

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Configure CPM cache path
        run: |
          echo "CPM_SOURCE_CACHE=$HOME/.cache/CPM" >> $GITHUB_ENV

      - name: Cache CPM packages
        uses: actions/cache@v4
        with:
          path: ${{ env.CPM_SOURCE_CACHE }}
          key: ${{ runner.os }}-cpm-packages-${{ hashFiles('**/CMakeLists.txt', 'CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            ${{ runner.os }}-cpm-packages-

      - uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Create ndkpath.txt
        run: |
          echo "$ANDROID_NDK_LATEST_HOME" > ./ndkpath.txt
          cat ./ndkpath.txt

      - name: QPM Action
        uses: Fernthedev/qpm-action@v1
        with:
          workflow_token: ${{ secrets.GITHUB_TOKEN }}
          restore: true
          cache: true
          publish: false

      - name: Build & create qmod
        run: |
          qpm s qmod

      - name: Get Library Name
        id: libname
        run: |
          cd ./build/
          pattern="lib${module_id}*.so"
          files=( $pattern )
          echo NAME="${files[0]}" >> $GITHUB_OUTPUT

      - name: Rename debug
        run: |
          mv ${GITHUB_WORKSPACE}/qmod/build/debug/${{ steps.libname.outputs.NAME }} ${GITHUB_WORKSPACE}/qmod/build/debug/debug_${{ steps.libname.outputs.NAME }}

      - name: Upload non-debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.libname.outputs.NAME }}
          path: ${{ github.workspace }}/qmod/build/${{ steps.libname.outputs.NAME }}
          if-no-files-found: error

      - name: Upload debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug_${{ steps.libname.outputs.NAME }}
          path: ${{ github.workspace }}/qmod/build/debug/debug_${{ steps.libname.outputs.NAME }}
          if-no-files-found: error

      - name: Upload qmod artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.qmodName }}.qmod
          path: ${{ github.workspace }}/qmod/${{ env.qmodName }}.qmod
          if-no-files-found: error
