name: Build Qmod

env:
  module_id: questeditor
  qmodName: QuestEditor

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'version*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./qmod

    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true

      - uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Create ndkpath.txt
        run: |
          echo "$ANDROID_NDK_LATEST_HOME" > ./ndkpath.txt
          cat ./ndkpath.txt

      - name: QPM Action
        uses: Fernthedev/qpm-action@main
        with:
          workflow_token: ${{ secrets.GITHUB_TOKEN }}

          restore: false
          cache: false

          publish: false

      - name: Restore
        run: |
          qpm restore

      - name: List Post Restore
        run: |
          echo includes:
          ls -la ./extern/includes
          echo libs:
          ls -la ./extern/libs

      - name: Create protobuf files
        run: |
          cd ..
          pwsh install_deps.ps1
          chmod +x ./make-proto.sh
          ./make-proto.sh
          cd ./qmod
          ls -la ./protobuf

      - name: Build & create qmod
        run: |
          qpm s qmod

      - name: Get Library Name
        id: libname
        run: |
          cd ./build/
          pattern="lib${module_id}*.so"
          files=( $pattern )
          echo NAME="${files[0]}" >> $GITHUB_OUTPUT

      - name: Rename debug
        run: |
          mv ./build/debug/${{ steps.libname.outputs.NAME }} ./build/debug/debug_${{ steps.libname.outputs.NAME }}

      - name: Upload non-debug artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.libname.outputs.NAME }}
          path: ./build/${{ steps.libname.outputs.NAME }}
          if-no-files-found: error

      - name: Upload debug artifact
        uses: actions/upload-artifact@v2
        with:
          name: debug_${{ steps.libname.outputs.NAME }}
          path: ./build/debug/debug_${{ steps.libname.outputs.NAME }}
          if-no-files-found: error

      - name: Upload qmod artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.qmodName }}.qmod
          path: ./${{ env.qmodName }}.qmod
          if-no-files-found: error
