name: "test-on-pr"

on: [pull_request]

# This workflow will build your tauri app without uploading it anywhere.

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install pnpm
        run: npm -g install pnpm # change this to npm or pnpm depending on which one you use
        
      - name: install frontend dependencies
        run: pnpm install # change this to npm or pnpm depending on which one you use

      # If tagName and releaseId are omitted tauri-action will only build the app and won't try to upload any asstes.
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
            # Name of the artifact to upload.
            # Optional. Default is 'artifact'
            name: tauri
        
            # A file, directory or wildcard pattern that describes what to upload
            # Required.
            path: |
                target/release/*
            # The desired behavior if no files are found using the provided path.
            # Available Options:
            #   warn: Output a warning but do not fail the action
            #   error: Fail the action with an error message
            #   ignore: Do not output any warnings or errors, the action does not fail
            # Optional. Default is 'warn'
            if-no-files-found: error